# Generated by Django 5.0.1 on 2024-02-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_cable_nep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='nep',
            field=models.BigIntegerField(default=0),
        ),
    ]
