# Generated by Django 5.0.1 on 2024-02-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_group_alter_cable_description_alter_cable_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='group',
            new_name='group_dev',
        ),
    ]
