# Generated by Django 5.0.1 on 2024-02-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_deva_cable_dev_a_devb_cable_dev_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='device',
        ),
    ]
