# Generated by Django 5.0.1 on 2024-02-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0009_remove_cable_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='dev_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_a', to='datacenter.device'),
        ),
        migrations.RemoveField(
            model_name='devb',
            name='name',
        ),
        migrations.AlterField(
            model_name='cable',
            name='dev_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_b', to='datacenter.device'),
        ),
        migrations.DeleteModel(
            name='DevA',
        ),
        migrations.DeleteModel(
            name='DevB',
        ),
    ]
