# Generated by Django 5.0.1 on 2024-02-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_alter_cable_dev_a_remove_devb_name_alter_cable_dev_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='nep',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_dev',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
